package com.example.kadan.dto.enums;

public enum ActivityType {
    USER_REGISTERED,
    USER_LOGIN,
    USER_UPDATE,
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    SETTLEMENT_ADDED,
}
